---
title: My first portfolio for Level 2 
author: Tau H
---
email: tau.hernaes@newham.ac.uk
description: I'm currently living in Kuching, Sarawak, Malaysia……a place like no other.

I'm a web designer and a lover of life.
# social links
twitter_username: twitterTau
github_username:  tbvuma

show_excerpts: true # set to false to remove excerpts on the homepage
